"""empty message

Revision ID: 09c3fd2087a7
Revises: 
Create Date: 2020-04-13 19:28:27.538306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c3fd2087a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('type1', sa.String(length=64), nullable=True),
    sa.Column('type2', sa.String(length=64), nullable=True),
    sa.Column('base_stat_speed', sa.Integer(), nullable=True),
    sa.Column('base_stat_spdef', sa.Integer(), nullable=True),
    sa.Column('base_stat_spatk', sa.Integer(), nullable=True),
    sa.Column('base_stat_atk', sa.Integer(), nullable=True),
    sa.Column('base_stat_def', sa.Integer(), nullable=True),
    sa.Column('sprites_back_default', sa.String(length=255), nullable=True),
    sa.Column('sprites_back_female', sa.String(length=255), nullable=True),
    sa.Column('sprites_back_shiny', sa.String(length=255), nullable=True),
    sa.Column('sprites_back_shiny_female', sa.String(length=255), nullable=True),
    sa.Column('sprites_front_default', sa.String(length=255), nullable=True),
    sa.Column('sprites_front_female', sa.String(length=255), nullable=True),
    sa.Column('sprites_front_shiny', sa.String(length=255), nullable=True),
    sa.Column('sprites_front_shiny_female', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
